import { Pool } from 'pg';
import { spawn } from 'child_process';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { pool as sharedPool } from '../db';
import {
  synthesizeMp3,
  preprocessForTTS,
  isConfigured,
  engineAvailable,
  engineIdentity,
  TTSEngine,
  VOICE_NAME,
  MODEL_ID,
  MAX_TTS_CHARS,
} from './tts.service';
import { logger } from '../logger';

/**
 * LibraryAudioService
 *
 * Narration audio for library entries, generated ON DEMAND and banked forever.
 *
 * Audio is synthesized once and banked forever: the MP3 lands in AUDIO_DIR and
 * every later play streams that same file straight off disk.
 *
 * Synthesis used to be on-demand only, because the archive is 4.5M characters
 * and pre-generating it on ElevenLabs would have cost roughly 4.5M credits.
 * Since 2026-08-07 the default engine is a local Kokoro model that is free at
 * any volume, so scripts/narrate-library.ts pre-generates the whole archive and
 * the on-demand path is now just the fallback for entries written since the
 * last pass.
 *
 * Two tiers, split by how new the entry is (2026-08-08):
 *
 *   An entry spends its first PREMIUM_WINDOW_DAYS days on hold — the nightly
 *   backfill will not touch it. If Matt asks for narration during those days,
 *   that request is a deliberate one (nothing in the app fetches audio on its
 *   own), so it is rendered on ElevenLabs/Kieron and banked as the premium
 *   voice. Past the window, and for the whole historical archive, it is Kokoro.
 *
 * A premium render is therefore always something Matt chose, never something a
 * schedule decided, which is why it is safe for it to cost money at all.
 *
 * Premium audio is terminal: once an entry is banked on ElevenLabs, nothing
 * regenerates it — not a GENERATION_VERSION bump, not an edit to the entry, and
 * never the backfill. Kokoro is free to redo; a paid render is not, and quietly
 * replacing Kieron with the local voice would be the worst outcome of the two.
 *
 * Entries are otherwise re-synthesized only when the content changes (hash
 * mismatch) or GENERATION_VERSION is bumped (voice/model/speed change).
 *
 * metadata.audio = { status, url, duration_sec, size_bytes, engine, voice,
 *                    model, speed, generation_version, content_hash,
 *                    generated_at, last_error?, last_attempt_at? }
 */

export const AUDIO_DIR = process.env.LIBRARY_AUDIO_DIR || '/home/matt/lucid_media/library';

// Bump to invalidate every banked MP3 (voice, model, or delivery change).
// 1 = Gemini / Enceladus (retired 2026-08-06), 2 = ElevenLabs / Kieron,
// 3 = local Kokoro / bm_daniel (2026-08-07) - free, so the whole archive is
// pre-generated by scripts/narrate-library.ts rather than banked on demand.
// 4 = same voice at speed 0.92 (2026-08-08). Bumped 79 entries into the
// backfill, so this re-narration costs about two nightly slices.
const GENERATION_VERSION = 4;

/**
 * How long a new entry is held back from the free backfill, and for how long a
 * request for it counts as the premium tap. Three days is Matt's number: long
 * enough that an entry written on a Friday is still premium-eligible on Sunday.
 */
export const PREMIUM_WINDOW_DAYS = Number(process.env.LUCID_PREMIUM_WINDOW_DAYS ?? 3);

/**
 * Ceiling on paid renders per calendar day (UTC). Nothing should be able to
 * reach it in normal use — it exists so that a client bug or a stuck retry
 * loop costs a handful of credits instead of an afternoon's worth. Past the
 * cap the render still happens, just on Kokoro, and the log says why.
 */
export const PREMIUM_DAILY_CAP = Number(process.env.LUCID_PREMIUM_DAILY_CAP ?? 5);

interface EntryRow {
  id: string;
  content: string | null;
  metadata: any;
  created_at: Date | string;
}

export interface AudioResult {
  path: string;
  cached: boolean;
}

export type AudioFailureCode =
  | 'not_found'
  | 'not_speakable'
  | 'too_long'
  | 'not_configured'
  | 'on_hold'
  | 'synthesis_failed';

/**
 * Whether a banked render came from the paid engine — the one thing that makes
 * an entry's audio untouchable. Read off the stamped engine, falling back to
 * the voice name for the handful of entries banked before `engine` was
 * recorded, so old ElevenLabs files are protected too.
 */
function isPremium(banked: any): boolean {
  if (!banked) return false;
  return banked.engine === 'elevenlabs' || banked.voice === 'Kieron';
}

export class AudioUnavailableError extends Error {
  code: AudioFailureCode;
  constructor(code: AudioFailureCode, message: string) {
    super(message);
    this.name = 'AudioUnavailableError';
    this.code = code;
  }
}

export class LibraryAudioService {
  private pool: Pool;
  /** Concurrent requests for the same entry share one synthesis. */
  private inFlight = new Map<string, Promise<AudioResult>>();

  constructor(pool: Pool) {
    this.pool = pool;
  }

  start(): void {
    fs.mkdirSync(AUDIO_DIR, { recursive: true });
    if (!isConfigured()) {
      logger.warn('[LIBRARY-AUDIO] ELEVENLABS_API_KEY not set — narration will 503 until it is');
      return;
    }
    const premium = engineIdentity('elevenlabs');
    logger.info(
      `[LIBRARY-AUDIO] On-demand narration ready (${VOICE_NAME}/${MODEL_ID}, dir ${AUDIO_DIR})`
    );
    logger.info(
      engineAvailable('elevenlabs')
        ? `[LIBRARY-AUDIO] Premium window: ${PREMIUM_WINDOW_DAYS}d on ${premium.voice}, ` +
            `max ${PREMIUM_DAILY_CAP}/day`
        : `[LIBRARY-AUDIO] Premium window disabled — no ELEVENLABS_API_KEY; everything renders on Kokoro`
    );
  }

  stop(): void {
    // Nothing scheduled — kept so the shutdown path stays uniform.
  }

  /**
   * Return the banked MP3 for an entry, synthesizing it first if this is the
   * first play (or the content changed since it was banked).
   *
   * `source` is what separates the two tiers: 'on-demand' is Matt asking for
   * this entry now, 'backfill' is the nightly script working through the
   * archive. Only the first can spend money, and only the second is subject to
   * the hold on new entries.
   */
  async ensureAudio(
    entryId: string,
    source: 'on-demand' | 'backfill' = 'on-demand'
  ): Promise<AudioResult> {
    const existing = this.inFlight.get(entryId);
    if (existing) return existing;

    const { rows } = await this.pool.query<EntryRow>(
      'SELECT id, content, metadata, created_at FROM library_entries WHERE id = $1',
      [entryId]
    );
    const row = rows[0];
    if (!row) throw new AudioUnavailableError('not_found', 'Entry not found');

    const text = preprocessForTTS(row.content || '');
    if (text.length === 0) {
      throw new AudioUnavailableError('not_speakable', 'Entry has no speakable text');
    }

    const filePath = path.join(AUDIO_DIR, `${entryId}.mp3`);
    const hash = sha256Hex(row.content || '');
    const banked = row.metadata?.audio;
    const hasFile = fs.existsSync(filePath);

    // A banked premium render is final. Deliberately checked before the hash
    // and version tests: an edit to the entry or a Kokoro voice change must not
    // be able to spend Matt's credits again, or worse, silently overwrite
    // Kieron with the local voice.
    if (isPremium(banked) && banked.status === 'ready' && hasFile) {
      return { path: filePath, cached: true };
    }

    const isFresh =
      banked?.status === 'ready' &&
      banked.content_hash === hash &&
      Number(banked.generation_version) === GENERATION_VERSION &&
      hasFile;

    if (isFresh) return { path: filePath, cached: true };

    const ageDays = (Date.now() - new Date(row.created_at).getTime()) / 86_400_000;
    const inWindow = ageDays < PREMIUM_WINDOW_DAYS;

    // The hold: the backfill leaves new entries alone so the premium window has
    // a chance to be used. They come back round on a later night.
    if (source === 'backfill' && inWindow) {
      throw new AudioUnavailableError(
        'on_hold',
        `Entry is ${ageDays.toFixed(1)} days old, inside the ${PREMIUM_WINDOW_DAYS}-day premium window`
      );
    }

    const engine = await this.chooseEngine(entryId, source, inWindow);

    if (!isConfigured()) {
      throw new AudioUnavailableError('not_configured', 'ELEVENLABS_API_KEY not set');
    }
    if (text.length > MAX_TTS_CHARS) {
      throw new AudioUnavailableError(
        'too_long',
        `Entry is ${text.length} chars, over the ${MAX_TTS_CHARS} limit`
      );
    }

    const job = this.generate(entryId, text, hash, filePath, engine).finally(() => {
      this.inFlight.delete(entryId);
    });
    this.inFlight.set(entryId, job);
    return job;
  }

  /**
   * Which engine renders this entry. Premium requires all three of: Matt asked
   * for it, the entry is still inside its window, and the day's paid budget has
   * room. Anything short of that is Kokoro, which is always available and never
   * costs anything — so this can degrade quietly rather than fail.
   */
  private async chooseEngine(
    entryId: string,
    source: 'on-demand' | 'backfill',
    inWindow: boolean
  ): Promise<TTSEngine> {
    if (source !== 'on-demand' || !inWindow) return 'kokoro';

    if (!engineAvailable('elevenlabs')) {
      logger.warn(
        `[LIBRARY-AUDIO] ${entryId} is inside the premium window but ELEVENLABS_API_KEY is not set — using Kokoro`
      );
      return 'kokoro';
    }

    const spent = await this.premiumRendersToday();
    if (spent >= PREMIUM_DAILY_CAP) {
      logger.warn(
        `[LIBRARY-AUDIO] ${entryId} is inside the premium window but today's paid cap is used ` +
          `(${spent}/${PREMIUM_DAILY_CAP}) — using Kokoro`
      );
      return 'kokoro';
    }

    logger.info(
      `[LIBRARY-AUDIO] ${entryId} inside the ${PREMIUM_WINDOW_DAYS}-day window — rendering premium ` +
        `(${spent + 1}/${PREMIUM_DAILY_CAP} today)`
    );
    return 'elevenlabs';
  }

  /**
   * Paid renders banked so far today, counted from the entries themselves
   * rather than a counter in memory. A pm2 restart mid-afternoon would reset an
   * in-process tally and hand back a fresh budget, which is exactly the failure
   * a cap is there to prevent.
   */
  private async premiumRendersToday(): Promise<number> {
    const { rows } = await this.pool.query<{ n: string }>(
      `SELECT count(*) AS n
         FROM library_entries
        WHERE metadata->'audio'->>'engine' = 'elevenlabs'
          AND (metadata->'audio'->>'generated_at')::timestamptz >= date_trunc('day', now())`
    );
    return Number(rows[0]?.n ?? 0);
  }

  private async generate(
    entryId: string,
    text: string,
    hash: string,
    filePath: string,
    engine: TTSEngine
  ): Promise<AudioResult> {
    const started = Date.now();
    const identity = engineIdentity(engine);
    logger.info(
      `[LIBRARY-AUDIO] Synthesizing ${entryId} (${text.length} chars, ${engine}/${identity.voice})`
    );

    try {
      const mp3 = await synthesizeMp3(text, engine);
      fs.mkdirSync(AUDIO_DIR, { recursive: true });
      const tmpPath = `${filePath}.tmp`;
      fs.writeFileSync(tmpPath, mp3);
      fs.renameSync(tmpPath, filePath);

      const sizeBytes = mp3.length;
      const durationSec = await probeDuration(filePath);

      await this.writeAudioMetadata(entryId, {
        status: 'ready',
        url: `/v1/library/${entryId}/audio`,
        duration_sec: durationSec,
        size_bytes: sizeBytes,
        engine,
        voice: identity.voice,
        model: identity.model,
        speed: identity.speed,
        generation_version: GENERATION_VERSION,
        content_hash: hash,
        generated_at: new Date().toISOString(),
      });

      logger.info(
        `[LIBRARY-AUDIO] Banked ${entryId}: ${engine}/${identity.voice}, ${durationSec}s, ` +
          `${Math.round(sizeBytes / 1024)}KB, ` +
          `${engine === 'elevenlabs' ? `${Math.round(text.length / 2)} credits` : 'free'}, ` +
          `${Math.round((Date.now() - started) / 1000)}s`
      );

      return { path: filePath, cached: false };
    } catch (err: any) {
      logger.error(`[LIBRARY-AUDIO] Failed ${entryId}`, { error: err.message });
      await this.writeAudioMetadata(entryId, {
        status: 'failed',
        last_error: String(err.message).slice(0, 300),
        last_attempt_at: new Date().toISOString(),
        generation_version: GENERATION_VERSION,
      }).catch(() => {});
      throw new AudioUnavailableError('synthesis_failed', err.message);
    }
  }

  private async writeAudioMetadata(id: string, audio: Record<string, unknown>): Promise<void> {
    await this.pool.query(
      `UPDATE library_entries
       SET metadata = jsonb_set(coalesce(metadata, '{}'::jsonb), '{audio}', $1::jsonb)
       WHERE id = $2`,
      [JSON.stringify(audio), id]
    );
  }
}

let instance: LibraryAudioService | null = null;

/** Shared instance — both server startup and the audio route use this one. */
export function getLibraryAudio(): LibraryAudioService {
  if (!instance) instance = new LibraryAudioService(sharedPool);
  return instance;
}

// --- helpers ---

function sha256Hex(text: string): string {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex');
}

/** Duration in whole seconds via ffprobe; 0 if it can't be read. */
function probeDuration(filePath: string): Promise<number> {
  return new Promise((resolve) => {
    const ff = spawn('ffprobe', [
      '-v', 'error',
      '-show_entries', 'format=duration',
      '-of', 'default=noprint_wrappers=1:nokey=1',
      filePath,
    ]);
    let out = '';
    ff.stdout.on('data', (d) => (out += d.toString()));
    ff.on('error', () => resolve(0));
    ff.on('close', () => {
      const seconds = parseFloat(out.trim());
      resolve(Number.isFinite(seconds) ? Math.round(seconds) : 0);
    });
  });
}

/**
 * The iOS app only routes playback to the server when metadata.audio.status is
 * "ready" (see LibraryEntry+Audio.swift), so with on-demand banking an entry
 * that has never been played would advertise nothing and the app would fall
 * back to on-device TTS — and never reach ElevenLabs at all.
 *
 * So advertise every speakable entry as playable. The URL is real: hitting it
 * synthesizes and banks on the spot. Entries already banked and fresh are left
 * exactly as they are, so their real generated_at keeps keying the phone cache.
 */
export function advertiseAudio<
  T extends { id: string; content?: string | null; metadata?: any; created_at?: Date | string }
>(entry: T): T {
  const content = entry.content || "";
  const text = preprocessForTTS(content);
  if (text.length === 0 || text.length > MAX_TTS_CHARS) return entry;

  const hash = sha256Hex(content);
  const banked = entry.metadata?.audio;
  // Premium first, for the same reason ensureAudio checks it first: a banked
  // Kieron render is current no matter what the hash or version say.
  if (isPremium(banked) && banked.status === "ready") return entry;
  if (
    banked?.status === "ready" &&
    banked.content_hash === hash &&
    Number(banked.generation_version) === GENERATION_VERSION
  ) {
    return entry;
  }

  // Advertise the tier the entry would actually get if Matt pressed play right
  // now, so the app can say which voice it is about to spend (or not spend) on.
  const ageDays = entry.created_at
    ? (Date.now() - new Date(entry.created_at).getTime()) / 86_400_000
    : Infinity;
  const pending: TTSEngine =
    ageDays < PREMIUM_WINDOW_DAYS && engineAvailable('elevenlabs') ? 'elevenlabs' : 'kokoro';
  const identity = engineIdentity(pending);

  return {
    ...entry,
    metadata: {
      ...(entry.metadata || {}),
      audio: {
        status: "ready",
        url: `/v1/library/${entry.id}/audio`,
        banked: false,
        engine: pending,
        voice: identity.voice,
        model: identity.model,
        speed: identity.speed,
        generation_version: GENERATION_VERSION,
        // Stable per content, so the phone re-downloads only after an edit.
        generated_at: `pending-${hash.slice(0, 16)}`,
      },
    },
  };
}
